<?php
/**
 * All list of certificates
 *
 * Space SSL Certificates
    261 => 'SpaceSSL Domain Validation (1 year)',
    262 => 'SpaceSSL Domain Validation (2 years)',
    263 => 'SpaceSSL Domain Validation (3 years)',
    271 => 'SpaceSSL WildCard (1 year)',
    272 => 'SpaceSSL WildCard (2 years)',
    273 => 'SpaceSSL WildCard (3 years)',
    211 => 'SpaceSSL MultiDomain 4 Domeny (1 year)',
    212 => 'SpaceSSL MultiDomain 4 Domeny (2 years)',
    213 => 'SpaceSSL MultiDomain 4 Domeny (3 years)',
    221 => 'SpaceSSL MultiDomain 6 Domen (1 year)',
    222 => 'SpaceSSL MultiDomain 6 Domen (2 years)',
    223 => 'SpaceSSL MultiDomain 6 Domen (3 years)',
    231 => 'SpaceSSL MultiDomain 10 Domen (1 year)',
    232 => 'SpaceSSL MultiDomain 10 Domen (2 years)',
    233 => 'SpaceSSL MultiDomain 10 Domen (3 years)',
    241 => 'SpaceSSL MultiDomain 100 Domen (1 year)',
    242 => 'SpaceSSL MultiDomain 100 Domen (2 years)',
    243 => 'SpaceSSL MultiDomain 100 Domen (3 years)',
 * ID Certificates Certificates
    731 => 'Basic ID (1 year)',
    732 => 'Basic ID (2 years)',
    733 => 'Basic ID (3 years)',
    711 => 'Professional ID (1 year)',
    712 => 'Professional ID (2 years)',
    713 => 'Professional ID (3 years)',
    721 => 'Enterprise ID (1 year)',
    722 => 'Enterprise ID (2 years)',
    723 => 'Enterprise ID (3 years)',
    791 => 'Test ID (90 days)',
 * Commercial Certificates
    601 => 'Commercial SSL (1 year)',
    602 => 'Commercial SSL (2 years)',
    603 => 'Commercial SSL (3 years)',
    741 => 'Commercial WildCard SSL (1 year)',
    742 => 'Commercial WildCard SSL (2 years)',
    743 => 'Commercial WildCard SSL (3 years)',
    651 => 'Commercial MultiDomain SSL 4 Domains (1 year)',
    652 => 'Commercial MultiDomain SSL 4 Domains (2 years)',
    653 => 'Commercial MultiDomain SSL 4 Domains (3 years)',
    661 => 'Commercial MultiDomain SSL 6 Domains (1 year)',
    662 => 'Commercial MultiDomain SSL 6 Domains (2 years)',
    663 => 'Commercial MultiDomain SSL 6 Domains (3 years)',
    671 => 'Commercial MultiDomain SSL 10 Domains (1 year)',
    672 => 'Commercial MultiDomain SSL 10 Domains (2 years)',
    673 => 'Commercial MultiDomain SSL 10 Domains (3 years)',
    961 => 'Commercial MultiDomain SSL 100 Domains (1 year)',
    962 => 'Commercial MultiDomain SSL 100 Domains (2 years)',
    963 => 'Commercial MultiDomain SSL 100 Domains (3 years)',
 * Trusted Certificates
    631 => 'Trusted SSL (1 year)',
    632 => 'Trusted SSL (2 years)',
    633 => 'Trusted SSL (3 years)',
    681 => 'Trusted WildCard SSL (1 year)',
    682 => 'Trusted WildCard SSL (2 years)',
    683 => 'Trusted WildCard SSL (3 years)',
    751 => 'Trusted MultiDomain SSL 4 Domains (1 year)',
    752 => 'Trusted MultiDomain SSL 4 Domains (2 years)',
    753 => 'Trusted MultiDomain SSL 4 Domains (3 years)',
    761 => 'Trusted MultiDomain SSL 6 Domains (1 year)',
    762 => 'Trusted MultiDomain SSL 6 Domains (2 years)',
    763 => 'Trusted MultiDomain SSL 6 Domains (3 years)',
    771 => 'Trusted MultiDomain SSL 10 Domains (1 year)',
    772 => 'Trusted MultiDomain SSL 10 Domains (2 years)',
    773 => 'Trusted MultiDomain SSL 10 Domains (3 years)',
    971 => 'Trusted MultiDomain SSL 100 Domains (1 year)',
    972 => 'Trusted MultiDomain SSL 100 Domains (2 years)',
    973 => 'Trusted MultiDomain SSL 100 Domains (3 years)',
    691 => 'Test SSL 1 domain (30 days)',
 * Premium EV Certificates
    641 => 'Premium EV SSL (1 year)',
    642 => 'Premium EV SSL (2 years)',
    643 => 'Premium EV SSL (3 years)',
    861 => 'Premium EV MultiDomain SSL 4 Domains (1 year)',
    862 => 'Premium EV MultiDomain SSL 4 Domains (2 years)',
    871 => 'Premium EV MultiDomain SSL 6 Domains (1 year)',
    872 => 'Premium EV MultiDomain SSL 6 Domains (2 years)',
    881 => 'Premium EV MultiDomain SSL 10 Domains (1 year)',
    882 => 'Premium EV MultiDomain SSL 10 Domains (2 years)',
    981 => 'Premium EV MultiDomain SSL 100 Domains (1 year)',
    982 => 'Premium EV MultiDomain SSL 100 Domains (2 years)',
 * Code Signing Certificates
    821 => 'Open Source Developer',
    841 => 'Standard Code Signing (1 year)',
    842 => 'Standard Code Signing (2 years)',
    843 => 'Standard Code Signing (3 years)',
    851 => 'Microsoft Code Signing (1 year)',
    852 => 'Microsoft Code Signing (2 years)',
    853 => 'Microsoft Code Signing (3 years)',
 *
 */
return [
    261 => 'certum_spacessl_domain_validation',
    271 => 'certum_spacessl_wildcard',
    241 => 'certum_spacessl_multidomain',
    731 => 'certum_basic_id',
    711 => 'certum_professional_id',
    721 => 'certum_enterprise_id',
    791 => 'certum_test_id',
    601 => 'certum_commercial_ssl',
    741 => 'certum_commercial_wildcard_ssl',
    961 => 'certum_commercial_multidomain_ssl',
    631 => 'certum_trusted_ssl',
    681 => 'certum_trusted_wildcard_ssl',
    971 => 'certum_trusted_multidomain_ssl',
    691 => 'certum_test_ssl',
    641 => 'certum_premium_ev_ssl',
    981 => 'certum_premium_ev_multidomain_ssl',
    821 => 'certum_open_source_developer',
    841 => 'certum_standard_code_signing',
    851 => 'certum_microsoft_code_signing',
];
